name: PY2
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - asttokens=3.0.0=pyhd8ed1ab_1
  - blosc=1.21.6=h85f69ea_0
  - brotli=1.1.0=hfd05255_4
  - brotli-bin=1.1.0=hfd05255_4
  - brotli-python=1.1.0=py310h73ae2b4_4
  - bzip2=1.0.8=h0ad9c76_8
  - c-blosc2=2.12.0=h183a6f4_0
  - ca-certificates=2025.10.5=h4c7d964_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=1.17.1=py310h29418f3_1
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - cpython=3.10.18=py310hd8ed1ab_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - debugpy=1.8.16=py310h699e580_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - fonttools=4.59.2=py310hdb0e946_0
  - freetype=2.14.1=h57928b3_0
  - glib=2.86.0=ha3795fc_0
  - glib-tools=2.86.0=he647baa_0
  - glpk=5.0=h8ffe710_0
  - gst-plugins-base=1.24.11=h3fe0a9e_0
  - gstreamer=1.24.11=h233a61a_0
  - h2=4.3.0=pyhcf101f3_0
  - h5py=3.8.0=nompi_py310h727aef9_101
  - hdf5=1.14.0=nompi_h918d9b7_103
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he0c23c2_0
  - idna=3.10=pyhd8ed1ab_1
  - igraph=0.10.13=hb4b56bc_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2025.2.0=h57928b3_757
  - ipykernel=6.30.1=pyh3521513_0
  - ipython=8.37.0=pyha7b4d00_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - joblib=1.5.2=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh5737063_0
  - kiwisolver=1.4.9=py310h1e1005b_1
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - leidenalg=0.10.2=py310h855be57_0
  - lerc=4.0.0=h6470a55_1
  - libaec=1.1.4=h20038f6_0
  - libblas=3.9.0=8_mkl
  - libbrotlicommon=1.1.0=hfd05255_4
  - libbrotlidec=1.1.0=hfd05255_4
  - libbrotlienc=1.1.0=hfd05255_4
  - libcblas=3.9.0=8_mkl
  - libclang13=21.1.1=default_ha2db4b5_0
  - libcurl=8.14.1=h88aaa65_0
  - libdeflate=1.24=h76ddb4d_0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.4.6=h537db12_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libglib=2.86.0=h5f26cbf_0
  - libhwloc=2.11.2=default_hc8275d1_1000
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libintl-devel=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.0=h2466b09_0
  - liblapack=3.9.0=8_mkl
  - libleidenalg=0.11.1=h91493d7_0
  - liblzma=5.8.1=h2466b09_2
  - libogg=1.3.5=h2466b09_1
  - libpng=1.6.50=h7351971_1
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.50.4=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libtiff=4.7.0=h550210a_6
  - libvorbis=1.3.7=h5112557_2
  - libwebp-base=1.6.0=h4d5522a_0
  - libxcb=1.16=h013a479_1
  - libxml2=2.13.8=h741aa76_1
  - libzlib=1.3.1=h2466b09_2
  - littleutils=0.2.4=pyhd8ed1ab_1
  - lz4-c=1.9.4=hcfcfb64_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - matplotlib=3.7.2=py310h5588dad_0
  - matplotlib-base=3.7.2=py310h51140c5_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - minepy=1.2.6=py310he2412df_2
  - mkl=2020.4=hb70f87d_311
  - mpir=3.0.0=he025d50_1002
  - mpmath=1.3.0=pyhd8ed1ab_1
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyhd8ed1ab_1
  - numpy=1.23.5
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numexpr=2.7.3=py310hf5e1058_2
  - openjpeg=2.5.3=h24db6dd_1
  - openssl=3.5.4=h725018a_0
  - outdated=0.2.2=pyhd8ed1ab_2
  - packaging=25.0=pyh29332c3_1
  - pandas=1.5.3=py310h1c4a608_1
  - pandas-flavor=0.7.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.46=h3402e2f_0
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=10.4.0=py310h3e38d90_1
  - pingouin=0.5.5=pyhd8ed1ab_1
  - pip=25.2=pyh8b19718_0
  - platformdirs=4.4.0=pyhcf101f3_0
  - ply=3.11=pyhd8ed1ab_3
  - pooch=1.8.2=pyhd8ed1ab_3
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.0.0=py310h29418f3_1
  - pthread-stubs=0.4=hcd874cb_1001
  - pthreads-win32=2.9.1=h2466b09_4
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-cpuinfo=9.0.0=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pynndescent=0.5.13=pyhd8ed1ab_1
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.15.11=py310h936fe8c_1
  - pyqt5-sip=12.17.0=py310h9e98ed7_1
  - pysocks=1.7.1=pyh09c184e_7
  - pytables=3.8.0=py310h1915493_1
  - python=3.10.18=h8c5b53a_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-igraph=0.11.5=py310h68d9e46_1
  - python_abi=3.10=8_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - pywin32=311=py310h282bd7d_1
  - pyzmq=27.1.0=py310h535538e_0
  - qt-main=5.15.15=hb098fff_5
  - requests=2.32.5=pyhd8ed1ab_0
  - scikit-learn=1.2.2=py310hd266714_2
  - scipy=1.10.1=py310h578b7cb_3
  - seaborn=0.12.2=hd8ed1ab_0
  - seaborn-base=0.12.2=pyhd8ed1ab_0
  - setuptools=80.9.0=pyhff2d567_0
  - sip=6.10.0=py310h9e98ed7_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h7fa0ca8_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tabulate=0.9.0=pyhd8ed1ab_2
  - tbb=2022.1.0=ha82c486_0
  - texttable=1.7.0=pyhd8ed1ab_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=h2c6b04d_2
  - toml=0.10.2=pyhd8ed1ab_1
  - tomli=2.2.1=pyhe01879c_2
  - tornado=6.5.2=py310h29418f3_1
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.26100.0=h57928b3_0
  - umap-learn=0.5.5=py310h5588dad_1
  - unicodedata2=16.0.0=py310h29418f3_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - vc=14.3=h41ae7f8_31
  - vc14_runtime=14.44.35208=h818238b_31
  - vcomp14=14.44.35208=h818238b_31
  - vs2015_runtime=14.44.35208=h38c0c73_31
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - xarray=2023.12.0=pyhd8ed1ab_0
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib-ng=2.0.7=hcfcfb64_0
  - zstandard=0.25.0=py310h1637853_0
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - absl-py==2.3.1
      - anndata==0.9.2
      - astunparse==1.6.3
      - bokeh==3.8.0
      - cachetools==5.5.2
      - click==8.2.1
      - contourpy==1.2.1
      - flatbuffers==25.2.10
      - gast==0.4.0
      - google-auth==2.40.3
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.75.0
      - imageio==2.37.0
      - jinja2==3.1.6
      - keras==2.11.0
      - lazy-loader==0.4
      - libclang==18.1.1
      - llvmlite==0.41.1
      - louvain==0.8.2
      - markdown==3.9
      - markupsafe==3.0.2
      - narwhals==2.5.0
      - natsort==8.4.0
      - networkx==3.4.2
      - numba==0.58.0
      - oauthlib==3.3.1
      - opt-einsum==3.4.0
      - protobuf==3.19.6
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pywavelets==1.4.1
      - pyyaml==6.0.2
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - scanpy==1.9.3
      - scikit-image==0.21.0
      - session-info==1.0.1
      - statsmodels==0.13.2
      - stdlib-list==0.11.1
      - stlearn==0.4.12
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.11.1
      - tensorflow-estimator==2.11.0
      - tensorflow-intel==2.11.1
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==3.1.0
      - tifffile==2025.5.10
      - torch==1.11.0
      - werkzeug==3.1.3
      - wrapt==1.17.3
      - xyzservices==2025.4.0
prefix: ./envs/conda/PY2
